# Generated by Django 5.0.6 on 2024-05-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('photo', models.ImageField(blank=True, upload_to='profile_photos/', verbose_name='Фото')),
            ],
        ),
    ]
