# Generated by Django 5.0.6 on 2024-05-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Шаблона')),
                ('description', models.TextField(verbose_name='описание')),
                ('photo', models.ImageField(blank=True, upload_to='profile_photos/', verbose_name='Фото')),
            ],
        ),
    ]
